### ISSUE TITLE
docker compose template

### ISSUE THREAD

**Issue by amigthea** [DRuggeri/nut_exporter#22]
how can configure docker compose in order to correctly retrieve the nut package informations? In my case the UPS is connected to the docker host via usb

this is my wip template:

```
  nut_exporter:
    container_name: nut_exporter
    hostname: nut_exporter
    image: ghcr.io/druggeri/nut_exporter:latest
    networks:
      docker-network:
        ipv4_address: <nut_exporter container address>
    environment:
      - NUT_EXPORTER_PASSWORD=<upsd.user password>
    command:
      - '--nut.server="<docker host address>"'
      - '--nut.username=<upsd.user username>'
      - '--nut.vars_enable="battery.charge,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,ups.load,ups.status"'
    restart: unless-stopped
```

I can reach the container metrics http page and scrape some default metrics (like promhttp_metric*) from prometheus but cannot connect the nut_exporter container to the docker host server, where nut package is installed, and get all the ups related metrics

`caller=nut_collector.go:82 level=error err="lookup \"<docker host address>\": no such host"`

I can successfully connect to the upsd server from another host at dockerhostaddress:3493, so the problem is on the container configuration.
- Is 3493 port defaulted on your container configuration?
- Maybe I need to add the ups name on the docker compose configuration?
