### ISSUE TITLE
network_ups_tools_ups_status metric is missing when using NUT_EXPORTER_VARIABLES

### ISSUE THREAD

**Issue by varac** [DRuggeri/nut_exporter#52]
I am using this `docker-compose.yaml` file: 

```yaml
services:
  nut-exporter:
    # https://github.com/DRuggeri/nut_exporter/pkgs/container/nut_exporter
    image: ghcr.io/druggeri/nut_exporter:3.1.1
    hostname: nut-exporter
    container_name: nut-exporter
    restart: unless-stopped
    ports:
      - 10.27.65.51:9199:9199/TCP
    environment:
      - NUT_EXPORTER_SERVER=10.27.65.51
      - NUT_EXPORTER_USERNAME=monitor
      - NUT_EXPORTER_PASSWORD=...
```

Everything work fine, the metrics `network_ups_tools_ups_status` is returned for different lables. 

But I'd like to get the content of more variables, so I set: 

    NUT_EXPORTER_VARIABLES="ups.realpower,ups.load,output.voltage,outlet.power,battery.runtime,battery.charge,battery.charge.low,battery.runtime.low"

With this, the metric  `network_ups_tools_ups_status` is missing completely.
How can I get more variables *and* have still the `network_ups_tools_ups_status` metric ?
